algorithm: "PPO"
learning_rate: 2.5e-4
num_envs: 4
num_steps: 128
total_timesteps: 1e5
update_epochs: 4
num_minibatches: 4
gamma: 0.99
gae_lambda: 0.95
clip_eps: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
activation: "tanh"
anneal_lr: True
seed: 0

env_name: "SimpleGridWorld-v0"
env_kwargs:
  grid_size: 5
  max_steps_in_episode: 20

wandb_entity: "drcope"
wandb_project: "ppo-gridworld-example"
wandb_mode: "online"